### PR TITLE
add explanation for iron Z and A values

### PR DESCRIPTION
**Pull request by RoyStegeman**

### CODE REVIEW

**Comment by RoyStegeman** [comment]
Wait, maybe I'm wrong since I don't find the values in the paper: https://arxiv.org/pdf/hep-ex/0102049

**Comment by alecandido** [comment]
> Wait, maybe I'm wrong since I don't find the values in the paper: [arxiv.org/pdf/hep-ex/0102049](https://arxiv.org/pdf/hep-ex/0102049)

As said in private communication, those numbers definitely came from APFEL, and the "I don't know comment" was the conservative one.
Maybe it could be just rephrased in a softer way... or left as it is...

**Comment by RoyStegeman** [comment]
Hi @enocera, do you perhaps know the source of the A and Z values for iron used in APFEL (and now yadism) predictions of NuTeV? I tried goodling and searching for those values in the nutev papers, but could not find their origin.

**Comment by enocera** [comment]
Hi @RoyStegeman the numbers are taken from A. Mason's PhD thesis, available at this link
https://inspirehep.net/files/15b639af43688d59f1ba65ec9cde7ec7
see in particular page 323 there.

**Comment by RoyStegeman** [comment]
Thanks, I would not have found that in a million years!

**Comment by alecandido** [comment]
> Thanks, I would not have found that in a million years!

Me too, thanks @enocera

**Review by alecandido — APPROVED** [review]

**Pull request merged**
