### PR TITLE
FONLL matching away from mass

### PR DESCRIPTION
**Pull request by felixhekhorn**
#168 provides a too complicated and potentially wrong solution to the problem at hand

It should be sufficient to just use the correct log, which is $Q^2/m^2$ and no $\mu$ - this instead can only appear in the atlas.

### TODO
- [x] drop mention of mu2 inside coefficient functions
- [x] write some documentation

### CODE REVIEW

**Comment by AleCandido** [comment]
@felixhekhorn why this is still draft?

**Comment by felixhekhorn** [comment]
I suggest to move

>  drop mention of mu2 inside coefficient functions

in a separate PR

**Comment by AleCandido** [comment]
> I suggest to move
> 
> > drop mention of mu2 inside coefficient functions
> 
> in a separate PR

Sorry, I already did it, but on the wrong branch (too similar names).

**Review by AleCandido — APPROVED** [review]
The only item I'm missing, that I'd like to still review, is the docs, but this I will read with ease from RTD after merged. And I'd not block the PR on that.

**Pull request merged**
