### PR TITLE
Fix pydocstyle

### PR DESCRIPTION
**Pull request by Radonirinaunimi**
It was strongly advised before to fix the pydocstyle in the same way as what was done in https://github.com/NNPDF/eko/pull/243 and hence the reason for this PR. I volunteered to do so and will do it incrementally, but everyone is invited to contribute.

- [ ] yadism
  - [ ] coefficient_functions
  - [ ] esf
  - [ ] input
- [ ] yadbox
   - [ ] runcards 
- [ ] yadmark
  - [ ] benchmark
  - [ ] data
  - [ ] navigator

### CODE REVIEW

**Comment by AleCandido** [comment]
Thanks @Radonirinaunimi, it's an annoying task, but useful.

However, since part of the task really consists in reviewing the docstrings, I would suggest you not to target (necessarily) completion. Even reducing the amount of errors might be enough, and a significant improvement.

**Comment by Radonirinaunimi** [comment]
> Thanks @Radonirinaunimi, it's an annoying task, but useful.
> 
> However, since part of the task really consists in reviewing the docstrings, I would suggest you not to target (necessarily) completion. Even reducing the amount of errors might be enough, and a significant improvement.

Yes, indeed! That'd be exactly the plan.

**Comment by felixhekhorn** [comment]
@Radonirinaunimi do you want to merge what is already here? just to not loose it? and convert the list into an issue?

**Comment by Radonirinaunimi** [comment]
> @Radonirinaunimi do you want to merge what is already here? just to not loose it? and convert the list into an issue?

My personal goal is to finish this before the Yadism paper appear. If that is not achieved, I agree that we can merge already what is here. But I haven't said my last words yet 😄

**Comment by felixhekhorn** [comment]
better push for the paper itself :innocent: or if you want to code, go for benchmarks

**Comment by Radonirinaunimi** [comment]
> better push for the paper itself 😇 or if you want to code, go for benchmarks

Absolutely! But this, if it will happen, will be for the outside hours.

**Pull request merged**
