### PR TITLE
Interpolate in eta n3lo grids

### PR DESCRIPTION
**Pull request by niclaurenti**
PR that modifies the N3LO massive grids coming from `adani`:
it will use rectangular grids in (`xi`, `eta`) done with  72 `eta` points log spaced from `1e-6` to `1e6` and 49 `xi` points log spaced from `1e-3` to `1e5`.

### CODE REVIEW

**Comment by AleCandido** [comment]
What's the estimated size of all grids?

**Comment by niclaurenti** [comment]
> What's the estimated size of all grids?

in total it should be 1.2 MB. I already computed them but before pushing I need to double check

**Comment by RoyStegeman** [comment]
Do you understand what happened? It looks like the grids are still about the same size?

**Comment by AleCandido** [comment]
Not really, they are two order of magnitudes smaller (200x)

image

**Comment by niclaurenti** [comment]
@giacomomagni could you verify that the results are almost unchanged

**Review by AleCandido — APPROVED** [review]
It seems alright

**Comment by giacomomagni** [comment]
> @giacomomagni could you verify that the results are almost unchanged

can you upload the new `xi` grid?

**Review by giacomomagni — CHANGES_REQUESTED** [review]
Unfortunately the test didn't go through: 
I got all the predictions full of `Nan`. 

I suspect that the `Nan` present in the grids for some points are screwing up all the thing. 
```
>>> np.load("C2q_nf3_var0.npy")
array([[ 1.74396910e-02,  2.77375221e-02,  4.39651615e-02, ...,
         5.31707582e+11,  7.82583775e+11,  1.15182312e+12],
       [ 1.05952714e-02,  1.68846156e-02,  2.67646579e-02, ...,
         3.58942868e+11,  5.28826749e+11,  7.79104948e+11],
       [ 6.30526825e-03,  1.00801082e-02,  1.59803316e-02, ...,
         2.45318146e+11,  3.61882664e+11,  5.33821310e+11],
       ...,
       [-1.30976513e-08, -1.36668952e-06,  1.54536462e-06, ...,
        -5.34225455e+05, -5.91282897e+05,             nan],
       [-2.31543882e-07, -1.67272049e-06,  2.21758109e-06, ...,
        -4.84729586e+05, -5.83190044e+05,             nan],
       [ 1.75987799e-07, -1.49978012e-06,  2.78479402e-06, ...,
        -4.25371522e+05, -5.38865318e+05, -6.43252602e+05]])
```

**Comment by niclaurenti** [comment]
> Unfortunately the test didn't go through: I got all the predictions full of `Nan`.
> 
> I suspect that the `Nan` present in the grids for some points are screwing up all the thing.
> 
> ```
> >>> np.load("C2q_nf3_var0.npy")
> array([[ 1.74396910e-02,  2.77375221e-02,  4.39651615e-02, ...,
>          5.31707582e+11,  7.82583775e+11,  1.15182312e+12],
>        [ 1.05952714e-02,  1.68846156e-02,  2.67646579e-02, ...,
>          3.58942868e+11,  5.28826749e+11,  7.79104948e+11],
>        [ 6.30526825e-03,  1.00801082e-02,  1.59803316e-02, ...,
>          2.45318146e+11,  3.61882664e+11,  5.33821310e+11],
>        ...,
>        [-1.30976513e-08, -1.36668952e-06,  1.54536462e-06, ...,
>         -5.34225455e+05, -5.91282897e+05,             nan],
>        [-2.31543882e-07, -1.67272049e-06,  2.21758109e-06, ...,
>         -4.84729586e+05, -5.83190044e+05,             nan],
>        [ 1.75987799e-07, -1.49978012e-06,  2.78479402e-06, ...,
>         -4.25371522e+05, -5.38865318e+05, -6.43252602e+05]])
> ```

If everybody agree we can just put to zero the `nans` since it is the very last point of some rows

**Comment by giacomomagni** [comment]
Yes, it should be some of the last points in the bottom right corner. 
Looking at the trend I don't see why should be 0, but if this works it's fine, 
and it isn't symptom of a further problem I'm okay.

**Comment by niclaurenti** [comment]
> Yes, it should be some of the last points in the bottom right corner. Looking at the trend I don't see why should be 0, but if this works it's fine, and it isn't symptom of a further problem I'm okay.

Well, there is no reason for putting it to zero, it is just a workaround until I will solve it in `adani`. But my guess is that it will not affect much the results since it it high $\eta$, i.e. small $x$.

Another option is that we do the same grids you did but with less points. That should work

**Pull request merged**
